[env]
_.file = ".env"

[tasks.start]
description = "Run the bot"
run = "go run ./cmd/dcc -prefix=test_"

[tasks.watch]
description = "Use watchexec to auto-rerun bot on code changes"
run = "watchexec -e .go go run ./cmd/dcc -prefix=test_"
